### ISSUE TITLE
Virus Total has 7 positve reports

### ISSUE THREAD

**Issue by Terry1031** [AsteriskAmpersand/MHR_Tex_Chopper#3]
I'm not sure about executing the file so I'd love to hear some feedback about it.

Here is the virus total link:

https://www.virustotal.com/gui/file/e166be5639bab84320648a5e41c115781f71d0cb5d15f2258a7cf4a87fc2bc07

**Comment by AsteriskAmpersand** [comment]
Then don't use it.

**Comment by Terry1031** [comment]
I'm not good enough with programming yet to take a look at the source code and check if it is safe or not but I was hoping there would a reason that could cause false positives.
