### ISSUE TITLE
Not Creat dds file version 0.5.1 execute

### ISSUE THREAD

**Issue by KentaroKurita** [AsteriskAmpersand/MHR_Tex_Chopper#4]
Thank you for making the tool!

The version 0.5.1 executable file could not be converted to a DDS file.

An execution example is as follows.

The version 0.5.1 

PS C:\Users\Administrator\Downloads\MHR_Tex_Chopper-main> .\Asterisk_MonsterHunterRise_Tex_Chopper.exe .\splas_IM.tex.28
Traceback (most recent call last):
  File "_main_MonsterHunterRise.py", line 10, in <module>
ModuleNotFoundError: No module named 'tex'
[3364] Failed to execute script '_main_MonsterHunterRise' due to unhandled exception!
PS C:\Users\Administrator\Downloads\MHR_Tex_Chopper-main>

The version 0.5.0

PS C:\Users\Administrator\Downloads\MHR_Tex_Chopper-main> .\Asterisk_MonsterHunterRise_Tex_Chopper.exe ".\splas.tex.28"
PS C:\Users\Administrator\Downloads\MHR_Tex_Chopper-main>

Version 0.5.0 created a DDS file.

Thank you.

**Comment by AsteriskAmpersand** [comment]
Fixed on latest release
